Remove OT_JOB + auto-init improved
jia200x/RIOT pull request #4
Opened 2017-05-29 13:16 UTC by biboc

Remove OT_JOB
Auto-init ifconfig with panid and channel (editable in Makefile) and start thread protocol
Address @aabadie comments

2017-05-29 13:18 UTC, aabadie commented on pkg/openthread/contrib/platform_alarm.c
> +        int dt;
Maybe int dt = aDt* ...

2017-05-29 13:20 UTC, aabadie commented on pkg/openthread/contrib/platform_radio.c
> +    if (state == NETOPT_STATE_OFF || state == NETOPT_STATE_SLEEP) {
return !(state == NETOPT_STATE_OFF || state == NETOPT_STATE_SLEEP) ?

2017-05-29 13:22 UTC, biboc commented on pkg/openthread/contrib/platform_radio.c
> +    if (state == NETOPT_STATE_OFF || state == NETOPT_STATE_SLEEP) {
No I prefer to do it in 5 lines, it is more understandable

2017-05-29 13:26 UTC, aabadie commented
Looks good to me. Can you merge it @jia200x  ?

2017-05-29 14:44 UTC, jia200x commented
Good!
The only thing I'm not sure about if it's a good idea to remove the OT_JOB functions (as commented in the openthread_core PR.

What do you think?

2017-05-29 15:22 UTC, biboc commented
I see what you mean. Actually, it is useful because all OpenThread functions become available from any other thread and it will use the right OpenThread instance.
I thought it was only for netdev functions. 
I mean, to change panid or any other setting, we have to use OpenThread function, I'll add an example in main.c, let me change my PR to see what I mean.

However, we need an unlimited number of ARGS instead of one job context (context is arg?)

2017-05-29 15:52 UTC, biboc commented
I would have suggested to continue with RIOT concept and use `gnrc_netapi_set/get` functions to communicate with openthread stack but it will miss some functionalities so I understand why you suggested OT_JOB finally. 

I think OT_JOB needs to more flexible so any kind of function can be called. At the moment, only function like `(otInstance*, void*)` can be called and no variable is returned so it is only for setter and printer.
If I need to know the channel in the thread `main`, I currently can't.

2017-05-29 17:30 UTC, biboc commented
In fact, what you did in main.c is what we needed! It's kind of wrapper functions!
Let's move these function in openthread contrib folder.

2017-05-29 18:43 UTC, biboc commented
In fact, there is a way to get the information back to the thread that call the OT_JOB: with context! It can be used for an arg or an answer. Good job @jia200x !
I'll edit my PR

2017-05-29 19:26 UTC, jia200x commented
> In fact, there is a way to get the information back to the thread that call the OT_JOB: with context! It can be used for an arg or an answer. Good job @jia200x !

Thanks :). That was the idea behind OT_JOB. It's possible to pass args and read returns with the context variable (maybe this can be improved though).

In the beginning I implemented IPC commands like netdev but I decided to go into the OT_JOB direction because ot API commands might change over time (also, it allows direct calls to otApi commands).

2017-05-30 07:37 UTC, biboc commented
@jia200x, tell me what you think about how I improved your OT_JOB
Btw, I'll do all command I think we need to access from RIOT (see in otJobs array)

2017-05-30 15:07 UTC, biboc commented
Done, tell me what you think.
I tried all functions and they work. The only thing is that you need to be careful about the type of argument `answer`

2017-06-01 08:21 UTC, biboc commented
Guys? @jia200x @aabadie

2017-06-01 12:46 UTC, aabadie commented
Will do some comments

2017-06-01 13:00 UTC, aabadie requested changes
Very good job @biboc. I have a few comments though. This goes into the right direction !

2017-06-01 13:00 UTC, aabadie commented on pkg/openthread/contrib/netdev/openthread_netdev.c
> -    _job.function = job;
no need for an underscore

2017-06-01 13:00 UTC, aabadie commented on pkg/openthread/contrib/netdev/openthread_netdev.c
> +    /* Init default parameters */
Stupid question: would it make sense to add these init calls in the openthread_bootstrap function ?

2017-06-01 13:00 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +} ot_job_command_t;
why not simply use ot_command_t ?

2017-06-01 13:00 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +} ot_job_command_t;
and rename OT_JOB to OT_COMMAND ?

2017-06-01 13:00 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +        printf("ERROR: ot_exec_job needs to run in OpenThread thread\n");
Use DEBUG

2017-06-01 13:00 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +    for (int i = 0; i < aLength; i++)
```c
for () {
[...]
}
```

2017-06-01 13:00 UTC, aabadie commented on tests/openthread/Makefile
> +BOARD_WHITELIST := samr21-xpro iotlab-m3 fox iotlab-a8-m3
would be great if we could add support to other 802.15.4 radios.

2017-06-01 13:00 UTC, aabadie commented on tests/openthread/main.c
> +    uint8_t res = ot_call_job("panid", NULL, (void*)&panid);
I would prefer to rename ot_call_job to ot_call_command. It makes more sense to me and looks more intuitive.

2017-06-01 13:35 UTC, biboc commented on pkg/openthread/contrib/netdev/openthread_netdev.c
> +    /* Init default parameters */
In bootstrap, `sInstance` is not init so we can't

2017-06-01 13:45 UTC, biboc commented
Done @aabadie

2017-06-01 13:46 UTC, biboc commented on tests/openthread/Makefile
> +BOARD_WHITELIST := samr21-xpro iotlab-m3 fox iotlab-a8-m3
Sure, let's merge this PR and people will add other 802.15.4 radios

2017-06-01 13:51 UTC, aabadie commented on pkg/openthread/contrib/netdev/openthread_netdev.c
> +uint8_t ot_call_command(char* name, void *arg, void* answer) {
maybe change `name` to `command`

2017-06-01 13:52 UTC, aabadie commented on pkg/openthread/contrib/netdev/openthread_netdev.c
> +    job.mName = name;
since job is defined in RIOT contrib code, use attribute that matches the RIOT code style:
job.command, job.arg, job.answer

2017-06-01 13:52 UTC, aabadie commented on pkg/openthread/contrib/netdev/openthread_netdev.c
> +    /* Init default parameters */
ok, that's fine for now

2017-06-01 13:54 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +    const char *mName;                              /**< A pointer to the job name string. */
use const char *name, align doxygen

2017-06-01 13:55 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +        otExtAddress extAddress;
s/extAddress/address/

2017-06-01 13:55 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +        otLinkModeConfig linkMode;
s/linkMode/link_mode

2017-06-01 13:56 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +        otLinkModeConfig linkMode;
well, no leave it like this

2017-06-01 13:56 UTC, aabadie commented on pkg/openthread/contrib/platform_functions_wrapper.c
> +        otExtAddress extAddress;
same here (sorry)

2017-06-01 14:02 UTC, biboc commented
Ok @aabadie, done

2017-06-01 14:49 UTC, jia200x commented
@biboc @aabadie Hi guys

Sorry for the late response, I was busy these days due to some IoT demos for the ITC (www.itcdigital.cl)

@biboc thanks a lot for the adoption of OT_COMMANDs. Awesome work!

2017-06-01 14:50 UTC, jia200x commented
if everything is OK, I will merge it. Let me know.

Cheers!

2017-06-01 14:54 UTC, aabadie commented
> if everything is OK, I will merge it. Let me know.
Yes, go ahead !

2017-06-01 14:55 UTC, biboc commented
Great!

2017-06-01 15:06 UTC, merged

2017-06-01 15:06 UTC, jia200x commented
Merged!